ALTER TABLE host_rollups_1m ADD COLUMN memory_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN network_rx_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN network_rx_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN network_rx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1m ADD COLUMN network_tx_min REAL;
ALTER TABLE host_rollups_1m ADD COLUMN network_tx_max REAL;
ALTER TABLE host_rollups_1m ADD COLUMN network_tx_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE host_rollups_15m ADD COLUMN memory_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN memory_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN memory_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN network_rx_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN network_rx_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN network_rx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_15m ADD COLUMN network_tx_min REAL;
ALTER TABLE host_rollups_15m ADD COLUMN network_tx_max REAL;
ALTER TABLE host_rollups_15m ADD COLUMN network_tx_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE host_rollups_1h ADD COLUMN memory_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN memory_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN memory_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN network_rx_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN network_rx_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN network_rx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE host_rollups_1h ADD COLUMN network_tx_min REAL;
ALTER TABLE host_rollups_1h ADD COLUMN network_tx_max REAL;
ALTER TABLE host_rollups_1h ADD COLUMN network_tx_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE resource_rollups_1m ADD COLUMN memory_min REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN memory_max REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN memory_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1m ADD COLUMN network_rx_min REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN network_rx_max REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN network_rx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1m ADD COLUMN network_tx_min REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN network_tx_max REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN network_tx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1m ADD COLUMN block_read_min REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN block_read_max REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN block_read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1m ADD COLUMN block_write_min REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN block_write_max REAL;
ALTER TABLE resource_rollups_1m ADD COLUMN block_write_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE resource_rollups_15m ADD COLUMN memory_min REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN memory_max REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN memory_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_15m ADD COLUMN network_rx_min REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN network_rx_max REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN network_rx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_15m ADD COLUMN network_tx_min REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN network_tx_max REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN network_tx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_15m ADD COLUMN block_read_min REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN block_read_max REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN block_read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_15m ADD COLUMN block_write_min REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN block_write_max REAL;
ALTER TABLE resource_rollups_15m ADD COLUMN block_write_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE resource_rollups_1h ADD COLUMN memory_min REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN memory_max REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN memory_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1h ADD COLUMN network_rx_min REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN network_rx_max REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN network_rx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1h ADD COLUMN network_tx_min REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN network_tx_max REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN network_tx_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1h ADD COLUMN block_read_min REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN block_read_max REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN block_read_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource_rollups_1h ADD COLUMN block_write_min REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN block_write_max REAL;
ALTER TABLE resource_rollups_1h ADD COLUMN block_write_count INTEGER NOT NULL DEFAULT 0;
